strawberry/package-lock.json
strawberry/package.json

chore/#8-install-react-router
- 라우팅에 필요한 리액트 라우터를 설치합니다.
- 리액트 라우터 설치 후 package 파일을 커밋하였습니다.
- closed: #8

리액트 라우터를 설치합니다.

---

strawberry/src/App.tsx
strawberry/src/modules/core/contexts/globalContext.tsx
strawberry/src/modules/core/hooks/useGlobalDispatch.tsx
strawberry/src/modules/core/hooks/useGlobalState.tsx

feature/#13-global-context-api
- 전역적으로 사용할 global context를 미리 정의합니다.
- 사용될 것이라고 예상되는 부분을 미리 작성해두었습니다.
- 필요에 따라 수정해나가면 될 것 같습니다!
- contexts 폴더를 추가하였습니다. => 다른 모듈에도 사용되는 context는 contexts 폴더 정의해서 사용하면 좋을 것 같습니다!
- 로그인 개발하시는대로 global context 사용해보시고 안되는 부분 말씀해주세요. 수정하겠습니다!
참고 자료: https://velog.io/@velopert/typescript-context-api
closed:#13

Global Context API를 추가합니다.

---

strawberry/package-lock.json
strawberry/package.json
strawberry/public/user.json
strawberry/src/App.tsx
strawberry/src/data/config/customError.tsx
strawberry/src/data/config/handleQueryError.tsx
strawberry/src/data/config/logging.tsx
strawberry/src/data/config/request.tsx
strawberry/src/data/config/response.tsx
strawberry/src/data/config/url.tsx
strawberry/src/data/config/useFetch.tsx
strawberry/src/data/example/user/useUserQuery.tsx

feature/#22-network-config
- 추후 사용될 네트워크 환경을 먼저 구성합니다.
- 저희 서버팀이 서버를 구축하고 나면 base url과 base response, error 등을 수정하도록 하겠습니다.
- 테스트 완료했습니다! => 사용해보고싶으시면 public 폴더에 json 파일 만들고 사용해보시면 됩니다.
- error 출력이 제대로 되는지는 테스트 다시 해봐야 할 것 같습니다
- 아래 data 폴더를 봐주세요.
- config는 네트워크 엔드포인트를 구현한 파일들입니당. error, request, response, fetch 등에 대한 베이스 코드를 구현하였습니다.
- 서버팀의 서버구축이 완료되면 연결 시도하고 필요한 부분 고치도록 하겠습니다.
사용방법
- response dto를 interface로 정의하여 사용합니다.
- fetch와 query를 하나로 묶어서 custom hook을 정의합니다.
- 이후 아래와 같이 작성하여 사용합니다.
- isLoading, isPending 등을 사용할 . 수있습니다.
- error 같은 경우에는 Alert 창이 뜰 수 있도록 구현하였지만 테스트는 못 해봤습니다.
```typescript
function Test() {
const { data } = useUserQuery();
return (
<>
<p> {data?.name} </p>
</>
);
}
export default App;
```
closed:#22

네트워크 Config를 구성하고 사용 예제를 만듭니다.

---

strawberry/src/pages/common/hooks/useNavigationBlock.tsx

- feat-#77-add-useNavigationBlocker
- 페이지 이동을 block하는 훅 추가
- common/hooks에 해당 코드 추가
- closed: #77

useNavigationBlocker를 구현합니다.

---

strawberry/src/pages/common/components/progress/SubmitProgress.tsx

- feat-#75-implement-SubmitProgress
- 퀴즈 정답 제출 진행 상황을 보여주는 progress bar 구현
- 구현 후 common components에 추가
- closed: #75

SubmitProgress를 구현합니다.

---

strawberry/src/data/config/useFetch.tsx

- feat-#73-modify-useFetch
- fetch를 시행하는 시점의 데이터를 body에 넘겨주기 위해 useFetch에 인자 추가
- useFetch를 선언할 때가 아닌, 해당 query, mutation을 사용할 때 body를 받도록 함
- closed: #73

useFetch를 수정합니다.

---

strawberry/src/pages/common/components/buttons/ModalButton.tsx
strawberry/src/pages/common/components/modal/Modal.tsx
strawberry/src/pages/common/components/modal/TwoButtonModal.tsx

- feat-#70-change-modal-style
- 모달 요소들의 스타일 변경
- 모달 bg의 zindex를 헤더보다 높게 설정
- 모달 버튼들의 width를 고정하지 않고, 버튼 wrapper의 gap을 통해 크기 조절
- closed: #70

모달 요소들의 스타일을 변경합니다.

---

strawberry/src/declarations.d.ts

- chore-#91-add-roughjs-declaration
- canvas의 roughjs 라이브러리 import 시 오류가 뜹니다.
- 최상위 폴더에 declare를 통해 해결하고자 합니다.
- 최상단 경로에 declarations.d.ts 파일 추가
- roughjs declare 코드 추가
- closed: #91

roughjs의 import를 위해 최상단 경로에 파일을 추가합니다.

---

strawberry/src/pages/common/components/modal/TwoButtonModal.tsx

- feat-#87-change-twobuttonmodal-css
- 상황별로 모달 레이아웃을 맞추기 위해 margin 코드 변경
- 이미지에서 top, bottom margin 주던 것을, 이미지 top margin/안내글 top margin으로 바꾸어 이미지 없이도 레이아웃 맞도록 수정
- closed: #87

TwoButtonModal의 레이아웃을 수정합니다.

---

strawberry/src/pages/quiz/components/quizBoard/QuizQuestion.tsx

- feat-#85-add-popover-in-quiz
- quizplay 페이지의 HintPopover를 구현된 Popover로 대체
- 해당 코드 추가 및 기존 코드 삭제
- closed: #85

QuizPlay페이지에 구현된 Popover를 적용합니다. 

---

strawberry/package.json

fix/#103-build
이슈 #103 참고해주세요.
빌드 명령어를 수정하여 빌드가 가능하도록 하였습니다.
closed: #103

Build가 되지 않는 오류를 수정합니다

---

strawberry/src/layout/components/header/LogoutButton.tsx

- fix-#100-add-logout-reload
- 안정적인 권한 관리를 위해 로그인을 해야 진입 가능한 페이지에서 로그아웃 시 reload 코드를 추가
- Logout Button onClick에 reload 코드 추가
- closed: #100

로그아웃 시 reload 코드를 추가합니다.

---

strawberry/src/pages/drawingPlay/DrawingPlayPage.tsx
strawberry/src/pages/drawingPlay/contexts/drawingPlayContext.tsx
strawberry/src/pages/drawingPlay/hooks/useDrawingCanvas.tsx
strawberry/src/pages/drawingPlay/models/DrawingPlayAction.tsx
strawberry/src/pages/drawingPlay/models/DrawingPlayState.tsx
strawberry/src/pages/drawingPlay/models/LineStyle.tsx
strawberry/src/pages/drawingPlay/models/Point.tsx
strawberry/src/pages/drawingPlay/models/index.tsx

refactor/#106-drawing-play
refactor/#106-drawing-play
- 모델 폴더를 추가하였습니다
- 
closed: #106

드로잉 플레이에 모델 폴더를 추가합니다.

---

strawberry/src/core/design_system/buttons/EventButton.tsx
strawberry/src/core/design_system/reset.css
strawberry/src/layout/components/footer/Footer.tsx
strawberry/src/layout/components/header/HeaderLogo.tsx

- fix-#114-build-image-font
- 이미지, 폰트 경로 수정을 통해 빌드 문제를 해결합니다.
- 이미지 src에 직접 반영을 import로 대체
- root에 기본 폰트를 적용하고 url을 추가
- closed: #114

빌드 시 이미지 경로와 폰트 문제를 해결합니다. 

---

strawberry/src/pages/drawingPlay/components/ProgressBar.tsx
strawberry/src/pages/drawingPlay/components/drawingOnboarding/DrawingOnboarding.tsx
strawberry/src/pages/drawingPlay/components/guide/DrawingGuideModal.tsx
strawberry/src/pages/drawingPlay/components/guide/GuideContent.tsx
strawberry/src/pages/drawingPlay/contexts/drawingPlayContext.tsx
strawberry/src/pages/drawingPlay/hooks/useDrawingOnboarding.tsx
strawberry/src/pages/drawingPlay/models/DrawingPlayState.tsx

- feat-#122-showing-guide-modal
- 1단계 OnBoarding 시에 가이드 모달을 보이도록 작업
- modal css 변경
- Onboarding에 해당 모달 추가
- progressbar 로직 수정
- closed: #122

드로잉 게임 시작 시에 가이드 모달을 보이게 합니다.

---

strawberry/src/pages/newCar/components/gallery/Gallery.tsx
strawberry/src/pages/newCar/hooks/useGallery.tsx

- feat-#134-add-gallery
- 신차 소개 페이지의 갤러리 컴포넌트를 구현합니다.
- 이미지 추가
- 컴포넌트 제작
- 훅 분리
- closed: #134

신차 소개 페이지의 갤러리 컴포넌트를 만듭니다.

---

strawberry/src/pages/common/components/toast/Toast.tsx
strawberry/src/pages/common/hooks/useToast.tsx

-fix-#128-add-toast
- 토스트 컴포넌트가 push 되지 않아 반영을 위해 다시 올립니다.
- 토스트, 훅 구현
- closed: #128

토스트를 추가합니다.

---

strawberry/src/pages/landing/hooks/useLandingBanner.tsx

- fix-#150-landing-scroll-button
- 랜딩 페이지 스크롤 버튼이 제대로 작동되지 않아 수정
- ref를 이미지 로딩 후에 잡도록 변경
- closed: #150

랜딩페이지의 스크롤 버튼 로직을 수정합니다.

---

strawberry/src/pages/common/components/modal/Modal.tsx
strawberry/src/pages/common/hooks/useModal.tsx

- feat-#182-add-modal-detail
- 모달에 편의를 위한 디테일을 추가합니다.
- 모달 open 시 다른 element 접근 불가
- esc 입력 시 twoButtonModal에서 whiteBtn 이벤트 실행(취소)
- esc 입력 시 oneButtonModal에서 primaryBtn 이벤트 실행
- 모달 open 시 blur처리
- 모달 close 시 이전 요소에 focus 처리
(ex: 퀴즈 오답 모달 후 다시 input에 focus)
- closed: #182

모달에 디테일을 추가합니다.

---

strawberry/src/pages/landing/components/landingBanner/LandingBanner.tsx

- design-#188-resize-landing-banner
- 랜딩페이지 배너 사이즈 조절
- css 변경
- closed: #188

랜딩페이지 배너의 사이즈를 조절합니다.

---

strawberry/src/pages/quizPlay/components/quizInput/CardInput.tsx

- feat-#190-input-highlight
- 퀴즈 정답 입력 시 입력할 칸을 한 눈에 볼 수 있도록 합니다.
- isHighlighted 속성을 추가하여 border 표시
- content의 길이, 추가/삭제 상태를 종합적으로 판단하여 표시
- closed: #190

퀴즈 플레이에서 입력 box를 hightlight하는 기능을 추가합니다. 

---

strawberry/src/pages/shared/SharedRedirectedPage.tsx

- fix-#195-share-redirect
- 누락된 페이지 추가
- 페이지 추가
- closed: #195

공유하기 리다이렉트 페이지를 추가합니다.

---

strawberry/src/pages/drawingPlay/services/calculateAverageDistance.ts
strawberry/src/pages/drawingPlay/services/extractInterpolatedPoints.ts
strawberry/src/pages/drawingPlay/services/interpolatePoints.ts

- fix-#198-drawingPlay-service
- 이전 pr의 누락된 service 로직 추가
- 코드 추가
- closed: #198

누락된 drawingPlay의 service 로직을 추가합니다.

---

strawberry/src/pages/newCar/contexts/NewCarContext.tsx
strawberry/src/pages/newCar/hooks/useNewCarDispatch.tsx
strawberry/src/pages/newCar/hooks/useNewCarState.tsx

feat/#200-newcar-context-hooks
- reudcer 함수를 수정하였습니다. 수정전처럼 사용하면 state 변경이 안되더라구용.. :(
- useContext hook을 생성하였습니다.
- useDispatch hook을 생성하였습니다.
closed: #200

신차소개에서 사용하는 context custom hook을 만듭니다.

---

strawberry/src/pages/login/hooks/useHandleLoginRedirect.tsx

- feat-#214-login-redirect-navigate
- 로그인 시도 후 원래 있던 창으로 복귀
- navigate(-2)로 변경
- closed: #214

로그인 후 원래 있던 페이지로 돌아가게 처리합니다.

---

strawberry/src/pages/drawingPlay/hooks/useDrawingFinish.tsx

- fix-#224-share-url
- 공유하기 url path 수정
- full url을 반환하도록 변경
- closed: #224

공유하기 url path를 수정합니다.

---

strawberry/src/pages/newCar/components/NewCarCarousel.tsx
strawberry/src/pages/newCar/components/driving/DrivingCarousel.tsx
strawberry/src/pages/newCar/components/gallery/NewCarGallery.tsx
strawberry/src/pages/newCar/components/space/SpaceBanner.tsx
strawberry/src/pages/newCar/components/space/SpaceCarousel.tsx
strawberry/src/pages/newCar/components/space/SpaceSeats.tsx
strawberry/src/pages/newCar/hooks/useGallery.tsx
strawberry/src/pages/newCar/models/NewCarCarouselItem.tsx
strawberry/src/pages/newCar/models/NewCarTypes.tsx
strawberry/src/pages/newCar/models/index.tsx

- feat-#230-newCar-below
- 신차 소개 페이지의 하단 부분을 구현합니다.
- Space 배너
- SpaceSeats 컴포넌트
- Technology Carousel 컴포넌트
- Hybrid Carousel 컴포넌트
- Gallery 컴포넌트
- closed: #230

신차 소개 페이지의 하단 부분을 완성합니다.

---

strawberry/src/data/entities/QuizResult.tsx
strawberry/src/data/queries/quiz/useQuizPlayMutation.tsx
strawberry/src/pages/quizPlay/hooks/usePrizeModal.tsx

- feat-#231-duplicated-participant
- 이미 참여한 유저에 대한 처리를 추가
- isParticipant 변수 추가
- usePrizeModal에 해당 모달 추가
- closed: #231

퀴즈 플레이 시 중복 참여자 체크 로직을 추가합니다.

---

strawberry/src/pages/quizLanding/hooks/index.tsx

- fix-#242-useQuizBanner-index
- 누락된 코드 추가
- 누락 코드 추가
- closed: #242

누락된 useQuizBanner를 index에 추가합니다.

---

strawberry/src/data/queries/drawing/useDrawingFinishQuery.tsx
strawberry/src/data/queries/drawing/useDrawingPlayQuery.tsx
strawberry/src/data/queries/drawing/useDrawingSharedQuery.tsx
strawberry/src/data/queries/expectation/useExpectationMutation.tsx

- feat-#245-drawing-finish-bonus
- DrawingFinish 화면에서 링크 공유, 기대평 작성 시에 기회 부분이 refetch 되도록 함
- 기대평 작성 시 EventUserInfo, DrawingInfo 쿼리 무효화
- 공유 링크 버튼 클릭 시 EventUserInfo, DrawingInfo 쿼리 무효화
- closed: #245

DrawingFinish 화면에서 링크 공유, 기대평 작성에 따른 추가 기회 로직을 추가합니다. 

---

strawberry/src/pages/quizPlay/QuizPlayPage.tsx
strawberry/src/pages/quizPlay/components/quizInput/CardInput.tsx
strawberry/src/pages/quizPlay/contexts/quizPlayContext.tsx
strawberry/src/pages/quizPlay/hooks/logics/useQuizPlayPage.tsx

- fix-#247-quiz-disabled-after-submit
- 오답을 계속 제출하는 상황을 방지
- isSubmitted 변수를 활용해 버튼과 input enter 방지
- closed: #247

기대평 제출 시 중복 제출 되는 현상을 해결합니다.

---

strawberry/src/pages/quizLanding/hooks/useQuizBanner.tsx

- fix-#279-merge-conflict
- conflict 해결 도중 지워진 코드를 추가
- 해당 코드 추가
- closed: #279

충돌 해결 중 지워진 코드를 추가합니다.

---

strawberry/src/pages/drawingPlay/hooks/useDrawingFinish.tsx
strawberry/src/pages/expectation/hooks/logics/useExpectationInput.tsx
strawberry/src/pages/quizPlay/QuizPlayPage.tsx
strawberry/src/pages/quizPlay/hooks/logics/useQuizPlayPage.tsx
strawberry/src/pages/quizPlay/hooks/usePrizeModal.tsx

- fix-#285-add-code
- 쓰로틀, 퀴즈 페이지 href, blank modal을 추가합니다.
- 퀴즈 제출 시 빈칸으로 제출하면 blank modal
- 기대평 페이지의 기대평 제출에 throttle
- drawingFinish의 기대평 제출에 throttle
- quiz 제출에 throttle
- quiz 관련 navgiate 코드를 href로 변경
- closed: #285

반영되지 않은 사항을 추가합니다.

---

strawberry/src/pages/drawingLanding/hooks/useDrawingBadges.tsx

- fix-#289-game-badge-overlay
- 기회 획득 로직을 수정합니다.
- > 0 조건을 >= 0 조건으로 수정
- closed: #289

보너스 기회 획득 후 사용하지 않았을 경우에도 overlay 처리를 추가합니다.

---

strawberry/src/pages/quizPlay/hooks/logics/useQuizPlayPage.tsx

- fix-#302-modify-bugs
- 쓰로틀 추가 후 오답 연속 제출 방지가 되지 않아 수정
- useMemo 의존성 배열에 isSubmitted 추가
- closed: #302

발견한 버그를 수정합니다.

---

strawberry/src/pages/drawingPlay/hooks/useDrawingFinish.tsx

- fix-#304-change-shared-redirect
- 단축 url을 위한 base url을 변경
- base url 변경
- closed: #304

공유 링크 리다이렉트 주소를 변경합니다.
