strawberry/src/App.tsx, strawberry/src/layout/DefaultLayout.tsx, strawberry/src/layout/HeaderLayout.tsx, strawberry/src/router/ProtectedRoute.tsx, strawberry/src/router/PublicRoute.tsx, strawberry/src/router/router.tsx
- feat-#20-implement-router
- path별로 page 할당을 위한 라우터 설정을 추가하여 App에 provider로 반영
- 라우터 파일에 path와 element 추가
- App 컴포넌트에 router provider 추가
- 레이아웃에 outlet 대신 children으로 대체(레이아웃 밑 페이지를 위한 요소, es-lint에서 children을 권장)
- 권한 여부 확인을 위한 Protected, Public route추가
- dummy file 제거
- closed: #20
=> 라우터 구조를 추가합니다.

strawberry/src/assets/images/icons/Arrow_Right_L_Black.svg, strawberry/src/assets/images/icons/Arrow_Right_L_White.svg, strawberry/src/core/design_system/buttons/EventButton.tsx, strawberry/src/core/design_system/color.tsx, strawberry/src/core/design_system/reset.css
- feat-#23-implement-EventButton
- 이벤트 페이지 구현 작업에 필요한 공통 컴포넌트인 이벤트 버튼을 구현합니다.
- reset.css에 DefaultButton 속성 추가 (DefaultButton 삭제 예정)
- 이벤트 버튼을 위한 white, black right arrow svg 파일 추가
- 이벤트 버튼 background color를 위한 색상을 Color에 추가
- 이벤트 버튼 구현
- 사용 방법
EventButton({ type, status, content, onClick })
ButtonType = "QUIZ" | "DRAWING"
ButtonStatus = "DEFAULT" | "DISABLED" | "EVENT_END"
content = ${넣고 싶은 내용}
onClick = function 클릭 시 실행하고 싶은 함수
좌측 3개 퀴즈 버튼, 우측 3개 드로잉 버튼 / 차례로 default, disabled, event_end
closed: #23
=> 이벤트 버튼을 구현합니다.

strawberry/src/core/design_system/color.tsx, strawberry/src/pages/quiz/components/CardInput.tsx
- feat-#25-implement-CardInput
- 퀴즈 이벤트 진행 페이지에서 사용자의 입력을 받을 컴포넌트를 만듭니다.
- CardInput 구현
- color에 common.white 추가
- 더미 파일 삭제
- closed: #25
=> 퀴즈 이벤트 페이지의 CardInput을 구현합니다.

strawberry/src/layout/DefaultLayout.tsx, strawberry/src/layout/HeaderLayout.tsx
- fix-#29-replace-router-children
- 라우터 설정 중 레이아웃의 nested Component를 받는 과정에서 children을 사용하였더니 페이지가 렌더링 되지 않아 수정
- 레이아웃의 children을 Outlet으로 수정
- closed: #29
=> 라우터의 children을 outlet으로 변경합니다. 

strawberry/src/layout/DefaultLayout.tsx, strawberry/src/layout/HeaderLayout.tsx
- feat-#31-add-Layout-css
- 레이아웃의 헤더, 푸터, 컨텐츠 영역의 css를 설정합니다.
- DefaultLayout css 적용
- HeaderLayout css 적용
- closed: #31
=> 레이아웃의 각 영역 크기에 대한 css를 설정합니다.

strawberry/src/core/contexts/globalContext.tsx, strawberry/src/data/config/url.tsx, strawberry/src/data/config/useFetch.tsx, strawberry/src/layout/HeaderLayout.tsx, strawberry/src/pages/login/LoginRedirectPage.tsx, strawberry/src/pages/login/hooks/useHandleLoginRedirect.tsx, strawberry/src/pages/login/hooks/useLogin.tsx, strawberry/src/pages/login/hooks/useLoginCallbackQuery.tsx, strawberry/src/router/ProtectedRoute.tsx, strawberry/src/router/router.tsx
feat/#55-social-login
- 소셜 로그인을 작업합니다.
- 현대, 네이버 둘 다 작업합니다.
- `.env` 파일 안에 url을 수정합니다. `/api/v1/` 은 useFetch안으로 옮겨두었습니다.
- protected route 기능을 추가해서, 토큰이 없는 경우(로그인 하지 않은 경우) play까지 도달하지 못 합니다.
- 직접 url을 쳐서 들어가도 로그인 유효성 검사 다시 합니다!
- token은 localStorage에 저장하였고, 일반적으로 저희는 global context 안에 있는 isLogin state를 사용하여 검사합니다.
closed: #55
=> 소셜 로그인을 구현합니다.

strawberry/src/core/utils/debounce.tsx, strawberry/src/core/utils/index.tsx, strawberry/src/core/utils/throttle.tsx, strawberry/src/pages/login/LoginPage.tsx
- feat/#57-avoid-duplicate-event-calls
- 불필요한 호출을 방지하는 기능을 추가합니다.
- 버튼 중복 터치, 스크롤 시 api 호출 등에 사용될 예정입니다.
- throttle
- debounce
다음 두 기능을 추가하였습니다.
사용방법 - 이벤트를 호출하는 곳에 throttle로 한 번 감싸서 사용합니다.
```typescript
const throttledLogin = throttle()((social: string) =>
login({ social: social }),
);
```
다음 스크린샷은 3G 배경에서의 콘솔창입니다.
- throttle 사용 전 -> clicked 무한 호출
https://github.com/user-attachments/assets/7b091db2-aa39-41e1-a89b-78cd4e94c552
- throttle 사용 후 -> clicked 한 번 호출 (set timer는 중복 이벤트가 들어왔음을 의미)
https://github.com/user-attachments/assets/6550f570-7ab4-42c8-b5f2-f4f4f6b8fc30
closed: #57
=> 중복 이벤트를 방지하는 기능을 추가합니다.

strawberry/src/layout/components/header/Header.tsx, strawberry/src/layout/components/header/LogoutButton.tsx
- feat-#69-change-header
- 헤더에 로그인 상태를 적용하고, 로그아웃 버튼을 구현합니다.
- 로그인 여부에 따라 로그인, 로그아웃 버튼 조건부 렌더링
- 로그아웃 버튼 디자인 변경, 로그아웃 로직 추가
- closed: #69
=> 헤더에 변경사항을 반영합니다.

strawberry/src/pages/expectation/ExpectationPage.tsx, strawberry/src/pages/expectation/ExpectationPageWrapper.tsx, strawberry/src/pages/expectation/components/ExpectationBanner.tsx, strawberry/src/pages/expectation/components/ExpectationInput.tsx, strawberry/src/pages/expectation/components/ExpectationList.tsx, strawberry/src/pages/expectation/components/ExpectationTitle.tsx, strawberry/src/pages/expectation/components/Pagination.tsx, strawberry/src/pages/expectation/contexts/expectationContext.tsx, strawberry/src/pages/expectation/contexts/useExpectationListQuery.tsx, strawberry/src/pages/expectation/hooks/apis/useExpectationListQuery.tsx, strawberry/src/pages/expectation/hooks/apis/useExpectationMutation.tsx, strawberry/src/pages/expectation/hooks/apis/useExpectationPageQuery.tsx, strawberry/src/pages/expectation/hooks/logics/useExpectationInput.tsx, strawberry/src/pages/expectation/hooks/logics/useExpectationPage.tsx, strawberry/src/pages/expectation/hooks/logics/usePagination.tsx, strawberry/src/pages/expectation/hooks/useExpectationData.tsx, strawberry/src/pages/expectation/hooks/useExpectationDispatch.tsx, strawberry/src/pages/expectation/hooks/useExpectationState.tsx, strawberry/src/pages/expectation/hooks/usePage.tsx, strawberry/src/router/router.tsx
- feat-#68-implement-expectation
- 기존 기대평 페이지에 API를 연동하여 페이지를 완성합니다.
- query, mutation 생성
- api 연동
- 커스텀 훅 생성
- throttle 적용
- wrapper 생성
- closed: #68
=> 기대평 페이지 API를 연동합니다.

strawberry/src/core/hooks/useCheckLogin.tsx, strawberry/src/pages/drawingLanding/components/drawingBanner/DrawingBanner.tsx, strawberry/src/pages/quizLanding/components/quizBanner/QuizBanner.tsx
feat/#79-link-to-event
- landing 페이지와 play 페이지 간의 이동을 추가합니다.
- useCheckLogin Hook을 만들었습니다! 로그인 유효성 검사를 해야 할 경우에 유용합니다.
```typescript
const navigate = useNavigate();
const checkLogin = useCheckLogin();
const handleEventClick = () => {
checkLogin(() => {
navigate("/drawing/play");
});
};
```
closed: #79
=> 로그인 상태를 검사하고 이벤트 페이지로 넘어갑니다.

strawberry/src/core/design_system/reset.css
- fix-#92-default-img-css
- 랜딩페이지 작업 중 이미지 사이 간격이 생기는 것을 해결하기 위해
- 해당 코드 reset.css에 추가
- closed: #92
=> reset.css에 이미지 veritcal-align을 top으로 설정합니다.

strawberry/src/core/utils/index.tsx, strawberry/src/core/utils/scrollTop.ts, strawberry/src/pages/landing/components/landingBanner/LandingBanner.tsx, strawberry/src/pages/landing/components/landingBanner/LandingBannerScrollButton.tsx, strawberry/src/pages/landing/hooks/useLandingBanner.tsx
- feat-#93-add-Landing-banner-scroll
- 랜딩페이지 스크롤 버튼에 동작을 추가합니다.
- scrollTop 유틸 함수 추가
- Banner에 관련 코드 추가 후 커스텀 훅으로 분리
- Button에서 height props로 받아 onClick 시 scrollTop 함수 실행 
- closed: #93
=> 랜딩 페이지 스크롤 동작을 추가합니다.

strawberry/src/core/hooks/useScrollToTop.tsx, strawberry/src/layout/DefaultLayout.tsx
- feat-#97-reset-navigate-scroll
- 라우터의 navigate로 페이지 이동 시 스크롤이 초기화 되지 않아 해결
- useScrollToTop 추가
- DefaultLayout에 해당코드 추가
- closed: #97
=> navigate 시 스크롤 초기화 코드를 추가합니다.

strawberry/src/data/entities/QuizLanding.tsx, strawberry/src/pages/quizLanding/components/quizBanner/QuizBanner.tsx
- feat-#119-quiz-event-button
- 현재 진행 중인 퀴즈 이벤트에 접속하기 위해 랜딩 페이지에서 받은 subEventId를 이벤트 참여 버튼에 매핑합니다.
- entity에 subEventId 속성 추가
- 버튼 경로 수정
- closed: #119
=> 퀴즈 랜딩 페이지의 참가 버튼에 게임 페이지 경로를 연결합니다. 

strawberry/src/core/design_system/reset.css, strawberry/src/data/entities/DrawingFinish.tsx, strawberry/src/data/entities/DrawingPlay.tsx, strawberry/src/data/entities/DrawingResult.tsx, strawberry/src/data/queries/drawing/useDrawingFinishQuery.tsx, strawberry/src/data/queries/drawing/useDrawingPlayMutation.tsx, strawberry/src/data/queries/drawing/useDrawingPlayQuery.tsx, strawberry/src/pages/drawingPlay/components/drawingFinish/DrawingFinish.tsx, strawberry/src/pages/drawingPlay/components/drawingGame/DrawingCanvas.tsx, strawberry/src/pages/drawingPlay/components/drawingResult/DrawingResult.tsx, strawberry/src/pages/drawingPlay/contexts/drawingPlayContext.tsx, strawberry/src/pages/drawingPlay/hooks/useDrawingCanvas.tsx, strawberry/src/pages/drawingPlay/hooks/useDrawingFinish.tsx, strawberry/src/pages/drawingPlay/hooks/useDrawingOnboarding.tsx, strawberry/src/pages/drawingPlay/hooks/useDrawingPlayPage.tsx, strawberry/src/pages/drawingPlay/hooks/useDrawingResult.tsx, strawberry/src/pages/drawingPlay/models/DrawingPlayAction.tsx, strawberry/src/pages/drawingPlay/models/DrawingPlayState.tsx
- feat-#121-add-drawing-play-api
- 드로잉 게임에 관한 모든 정보를 서버에서 받아옵니다.
- 쿼리, 뮤테이션 추가
- entity 추가
- OnBoarding, Game, Result, Finish에 서버 정보 반영
- 모달 로직 수정
- font path 수정
- closed: #121
=> 드로잉 게임에 게임 정보 API를 연동합니다.

strawberry/src/pages/drawingPlay/components/drawingOnboarding/DrawingOnboarding.tsx, strawberry/src/pages/drawingPlay/hooks/useProgressBar.tsx
- fix-#124-modify-progress-logic
- 모달이 띄워진 상태에서 프로그래스바가 1초부터 시작하는 현상이 발생하여 해결
- 로직 변경
- closed: #124
=> 드로잉 게임 progressbar 로직을 수정합니다.

strawberry/src/pages/quizPlay/QuizPlayPage.tsx, strawberry/src/pages/quizPlay/components/quizInput/CardInput.tsx
- feat-#149-enter-answer
- UX 향상을 위해 엔터 답안 제출, 오답 모달 이후 포커스 기능을 추가
- input에 enter를 감지하는 keyDown 이벤트 추가
- input에 isModalOpen 기반의 focus 코드를 추가
- closed: #149
=> 퀴즈 플레이 시 엔터로 답안을 제출하고, 오답 모달을 닫고 인풋에 포커스 되도록 합니다.

strawberry/src/pages/newCar/components/newCarBottom/NewCarBottom.tsx
- feat-#155-implement-NewCar-Bottom
- 신차 소개 페이지에서 사용하는 Bottom 컴포넌트 구현
- 컴포넌트 구현
- closed: #155
=> 신차 소개 페이지의 버튼을 포함하는 bottom 컴포넌트를 구현합니다. 

strawberry/src/layout/components/header/CarIntroButton.tsx, strawberry/src/layout/components/header/Header.tsx, strawberry/src/layout/components/header/LoginButton.tsx, strawberry/src/layout/components/header/LogoutButton.tsx
- design-#158-header-button-css
- 화면 크기가 달라질 때를 위해 버튼의 크기를 padding으로만 조절
- width, height 제거
- 버튼 간격 gap으로 조절
- closed: #158
=> 헤더의 버튼 width, height를 제거합니다.

strawberry/public/assets/icons/retry_disabled.svg, strawberry/src/core/design_system/ImageEnum.ts, strawberry/src/data/queries/drawing/useDrawingPlayQuery.tsx, strawberry/src/data/queries/drawing/useDrawingSharedQuery.tsx, strawberry/src/data/queries/expectation/useExpectationMutation.tsx, strawberry/src/pages/common/hooks/useToast.tsx, strawberry/src/pages/drawingPlay/components/drawingFinish/DrawingFinish.tsx, strawberry/src/pages/drawingPlay/components/drawingFinish/DrawingInput.tsx, strawberry/src/pages/drawingPlay/hooks/useDrawingCanvas.tsx, strawberry/src/pages/drawingPlay/hooks/useDrawingFinish.tsx, strawberry/src/pages/expectation/hooks/logics/useExpectationInput.tsx
- feat-#154-retry-button-logic
- 드로잉 결과 페이지 디테일 사항 추가
- 기대평 작성 후 toast, button disabled
- 기대평 작성 api 연동
(기대평 기회 부분 추가해야 합니다)
- closed: #154
=> 드로잉 결과 페이지의 디테일 사항을 추가합니다.

strawberry/src/core/contexts/globalContext.tsx, strawberry/src/pages/common/components/modal/OneButtonModal.tsx, strawberry/src/pages/quizPlay/components/quizInput/CardInput.tsx, strawberry/src/pages/quizPlay/hooks/usePrizeModal.tsx
- feat-#152-OneButtonModal-close
- 퀴즈 이벤트 진행 시 OneButtonModal에서 버튼 클릭 대신 enter로 대체할 수 있도록 기능 추가
- globalContext에 enter property 추가
- usePrizeModal에 enter 속성 추가
(OneButtonModal은 버튼이 한 개이므로 따로 엔터 callback을 넣어주지 않고, onClick 이벤트가 실행되도록 처리했습니다.)
- closed: #152
=> OneButtonModal에 Enter로 close할 수 있는 기능을 추가합니다.

strawberry/src/data/queries/quiz/useQuizPlayQuery.tsx
- feat-#173-quiz-play-error
- 퀴즈 이벤트 기간이 아님에도 페이지 진입 시를 처리
- query의 onError에 alert후 페이지 이동 코드 추가
- closed: #173
=> 퀴즈 이벤트 진입 시 이벤트 기간이 아닐 때의 경우를 처리합니다. 

strawberry/src/pages/drawingPlay/components/drawingGame/DrawingCanvas.tsx, strawberry/src/pages/drawingPlay/hooks/useDrawingCanvas.tsx
- feat-#180-add-drawing-play-detail
- 드로잉 게임에 디테일한 사항을 추가합니다.
- 드로잉 캔버스를 벗어났을 때 게임 종료 (상의 후 수정 예정)
- 캔버스 바운더리 표시 (상의 후 수정 예정)
- 게임 플레이 도중 element가 drag 되는 현상 방지
- 시작 후 start버튼 end 버튼으로 변경
- end 버튼에 도착하면 게임 종료
- end 버튼에 도착하면 시작점과 끝점 이어 그림 완성(end버튼에 도착하지 않으면 그림 이어지지 않음)
- 보간법을 사용하여 점 보정 후 서버로 요청
- 리팩토링, 주석 추가
(일단 임의로 바운더리 설정하였고 이에 대해 논의해봐야 합니다!)
- closed: #180
=> 드로잉 게임의 디테일을 추가합니다.

strawberry/src/pages/quizPlay/components/quizInput/CardInput.tsx
- fix-#192-card-highlight
- content.length === 0일 때 card를 클릭하면 hightlight가 풀리는 현상을 해결
- Math.max를 통해 length가 0일 때 0번째 card가 highlight 되도록 변경
- closed: #192
=> 퀴즈 플레이 시 card를 클릭하면 hightlight 해제되는 현상을 해결합니다.

strawberry/src/pages/newCar/components/FoundationButton.tsx, strawberry/src/pages/newCar/components/FoundationRadioButton.tsx, strawberry/src/pages/newCar/components/design/ExteriorCalligraphy.tsx, strawberry/src/pages/newCar/components/design/NewCarDesignDetail.tsx, strawberry/src/pages/newCar/models/Calligraphy.tsx
feat/#197-radio-button
신차 소개에 사용되는 라디오 버튼을 만들었습니당 :)
- context api를 사용하여 상태 관리를 하기 때문에, useState 대신 context를 넘길 수 있는 방안을 모색해보았습니당.
- 넘기는 프롭스들이 많네요 ㅜㅜ 더 쉽게 관리할 수 있는 방법이 생각나시면 말씀해주세용 :) => pr 작성하면서 생각해버렸습니당....
원래는 제네릭 타입 3개를 써서, state와 dispatch를 모두 받게 코딩했는데 생각해보니 그럴 필요가 전혀 없었네요...
미리 정의 된 state와 함수를 넘기면 되는거였네용 ... ㅜㅜ
=> props도 2개 줄이고, 제네릭도 2개 줄일 수 있었어요... 행복합니다...:)
1. 라디오 버튼 안에 들어갈 버튼들을 객체 배열로 만든다 => buttons
2. 버튼이 눌렀을 때 실행되어야 할 action을 미리 정의한다 => actionCreator
3. 변경되어야 하는 context state를 미리 정의한다. => selector
4. 제네릭 타입에 radio button value type을 넘겨줍니당 :)
**사용법**
```typescript
const buttons = [
{ title: "캘리그래피", value: "NORMAL" as ExteriorCalligraphyType },
{
title: "캘리그래피(블랙잉크)",
value: "BLACKINK" as ExteriorCalligraphyType,
},
];
const state = useNewCarState();
const dispatch = …
```
=> 라디오버튼을 만듭니다.

strawberry/generateImageEnum.cjs, strawberry/src/pages/drawingPlay/components/drawingFinish/DrawingFinish.tsx
- feat-#202-add-celebration-gif
- url로 사용하던 gif를 로컬에 저장하여 대체합니다.
- gif 추가
- generateImageEnum에 gif 확장자 추가
- url을 gif path로 변경
- closed: #202
=> 드로잉 결과 페이지의 gif를 추가합니다.

strawberry/src/data/entities/DrawingLanding.tsx, strawberry/src/data/queries/drawing/useDrawingFinishQuery.tsx, strawberry/src/data/queries/drawing/useDrawingPlayMutation.tsx, strawberry/src/data/queries/drawing/useDrawingPlayQuery.tsx, strawberry/src/data/queries/drawing/useDrawingSharedQuery.tsx, strawberry/src/pages/drawingLanding/components/drawingBanner/DrawingBanner.tsx, strawberry/src/pages/drawingPlay/hooks/useDrawingCanvas.tsx, strawberry/src/pages/drawingPlay/hooks/useDrawingFinish.tsx, strawberry/src/pages/drawingPlay/hooks/useDrawingPlayPage.tsx, strawberry/src/router/router.tsx
- feat-#194-add-subEventId
- 드로잉에서의 subEventId를 처리합니다.
- 드로잉 게임 pathparam 추가
- 임의로 설정한 subEventId useParam 처리
- 드로잉 랜딩 이벤트 버튼에 subEventId 처리
- closed: #194
=> subEventId에 대한 처리를 추가합니다. 

strawberry/src/pages/common/components/error/NotFound.tsx, strawberry/src/pages/error/NotFound.tsx, strawberry/src/router/router.tsx
- feat-#186-add-404
- 지정되지 않은 경로로 진입했을 때의 NotFound 페이지를 제작합니다.
- 페이지 구현
- 라우터에 path 지정 후 추가
- closed: #186
=> 404페이지를 추가합니다.

strawberry/src/core/contexts/globalContext.tsx, strawberry/src/pages/common/components/modal/Modal.tsx, strawberry/src/pages/common/components/modal/ProgressModal.tsx, strawberry/src/pages/common/components/progress/SubmitProgress.tsx, strawberry/src/pages/common/hooks/useSubmitProgress.tsx, strawberry/src/pages/quizPlay/hooks/logics/useQuizPlayPage.tsx
- feat-#218-add-Progress-modal
- 선착순 퀴즈 이벤트에서 답변 제출 결과를 기다릴 모달 추가
- ProgressModal 구현
- modal type에 추가
- 답변 제출 mutation의 isLoading을 기반으로 modal open (0.2초 안에 응답이 오면 로딩 모달 띄우지 않음)
- progress transition 로직 수정 (렌더링 직후 바로 게이지가 차도록 수정)
- closed: #218
=> 선착순 퀴즈 제출 시 pending 상태에서의 모달을 추가합니다. 

strawberry/src/pages/landing/components/landingEvent/CountdownTimer.tsx
- fix-#216-landing-quiz-remain-zero
- 퀴즈 오픈까지의 시간이 0일 때의 버그를 수정
- 남은 시간이 0일 때 처리
- closed: #216
=> 랜딩페이지에서 퀴즈 remainTime이 0일 때를 처리합니다.

strawberry/src/data/queries/eventUser/useEventUserInfoQuery.tsx, strawberry/src/pages/drawingLanding/components/drawingBanner/DrawingBanner.tsx, strawberry/src/pages/drawingLanding/components/drawingRank/MyDrawingScore.tsx, strawberry/src/pages/drawingLanding/hooks/useDrawingBanner.tsx
- feat-#213-not-login-drawing-landing
- 로그인하지 않았을 때의 드로잉 랜딩 페이지를 처리
- EventInfoQuery에 로그인하지 않았을 경우 패치하지 않는 속성 추가 (오류 해결)
- 로그인하지 않았을 경우 이벤트 버튼 활성화, infoMsg 숨김
- 로그인하지 않았을 경우 내 최고 점수 "-"로 처리
- closed: #213
=> 로그인하지 않았을 때의 드로잉 랜딩 페이지를 처리합니다.

strawberry/src/pages/quizLanding/components/quizBanner/QuizBanner.tsx, strawberry/src/pages/quizLanding/components/quizOpen/QuizEventEnd.tsx, strawberry/src/pages/quizLanding/components/quizOpen/QuizOpen.tsx, strawberry/src/pages/quizLanding/components/quizOpen/QuizOpenStep.tsx, strawberry/src/pages/quizLanding/hooks/useQuizOpenStep.tsx
- feat-#174-quiz-landing-detail
- 퀴즈 랜딩 페이지의 디테일 추가
- 진행 중인 퀴즈에 따른 ui 반영
- 이벤트 종료 시에 보여줄 component 구현 후 추가
- 이벤트 종료 시 event_end 버튼
> 백엔드 quizSequence 변경하면 step 제대로 반영
- closed: #174
=> 퀴즈 랜딩 페이지의 오늘의 문제, 이벤트 참여 버튼 디테일을 추가합니다.

strawberry/src/pages/quizPlay/components/quizInput/CardInput.tsx
- feat-#226-blur-highlight
- focus되지 않은 상태에서 hightlight를 해제합니다.
- isFocused 변수를 통해 관리
> input 이외의 element 클릭 시 highlight 해제
> 정답 제출 시 focus 해제 되며 highlight가 해제
- closed: #226
=> 퀴즈 플레이 input 이외의 element 클릭 시 hightlight를 해제합니다. 

strawberry/src/data/queries/drawing/useDrawingRankQuery.tsx, strawberry/src/data/queries/eventUser/useEventUserInfoQuery.tsx, strawberry/src/pages/drawingLanding/components/drawingBanner/DrawingBanner.tsx, strawberry/src/pages/drawingLanding/components/drawingBanner/DrawingChance.tsx, strawberry/src/pages/drawingLanding/hooks/useDrawingBanner.tsx, strawberry/src/pages/drawingLanding/hooks/useDrawingLandingData.tsx
- fix-#233-drawing-init
- 게임에 처음 참여하는 유저가 eventUserInfo를 불러오는 과정에 문제가 생겨 이를 해결 후 처음 게임 참여 경우 추가
- queery들의 실행 순서 추가
- useEventUserQuery에서 404일 시 pass
- eventUserData를 통한 isFrist 변수를 통해 처음 참여 유저인지 판별
- 해당 케이스에 대한 문구, 버튼 활성화 로직 추가
> 처음 게임에 참여하는 경우
> 로그인하지 않은 경우
- closed: #233
=> 이벤트에 처음 참가하는 유저가 정상적으로 드로잉게임을 진행할 수 있도록 합니다.

strawberry/src/data/queries/user/useLoginCallbackQuery.tsx, strawberry/src/pages/login/hooks/useDuplicatedSignUpModal.tsx
- feat-#232-duplicated-sign-up
- 중복 회원가입(sns 로그인) 시를 처리합니다.
- useLoginRedirectQuery의 error 로직 수정
- useDuplicatedSignUpModal 추가
- closed: #232
=> 중복 회원가입 시 로직을 처리합니다.

strawberry/src/pages/common/components/modal/OneButtonModal.tsx, strawberry/src/pages/quizLanding/components/quizBanner/QuizBanner.tsx, strawberry/src/pages/quizLanding/components/quizOpen/QuizOpenStep.tsx, strawberry/src/pages/quizLanding/hooks/useQuizBanner.tsx
- feat-#240-quiz-land-end
- 퀴즈 랜딩 페이지에서 이벤트가 모두 끝났을 때를 처리
- OneButtonModal에 whiteBtn 요소 추가
- openstep 로직 변경
- QuizBanner에 모달 로직 추가
- closed: #240
=> 퀴즈 랜딩 페이지에서 모든 이벤트의 기간이 끝났을 때를 처리합니다.

strawberry/src/App.tsx, strawberry/src/data/queries/expectation/useExpectationListQuery.tsx, strawberry/src/data/queries/expectation/useExpectationPageQuery.tsx
- fix-#250-refetch-on-window-focus
- 해당 속성이 default true인 상태에서 문제가 생겨 false로 고치고, 이 속성이 필요한 쿼리에서 true로 추가합니다.
- App 컴포넌트 내에 속성 false로 추가
- 해당 속성이 필요한 쿼리에서 추가
- closed: #250
=> 리액트 쿼리의 focus 전환 시 패치 로직을 수정합니다.

strawberry/src/layout/components/header/CarIntroButton.tsx
- fix-#249-visit-santafe-button
- 해당 버튼의 컨텐츠가 두줄로 나오는 현상이 있어 이를 해결합니다.
- white-space: nowrap 속성 추가
- closed: #249
=> 싼타페 보러가기 버튼에 nowrap 속성을 추가합니다.

strawberry/src/pages/quizLanding/hooks/useQuizBanner.tsx
- fix-#248-event-end-modal
- 이벤트 기간이 맞지만 아니라는 모달이 뜨는 현상을 수정합니다.
- useEffect 안에 return 문을 추가하여 해당 컴포넌트가 unmount 시에 clear modal
- closed: #248
=> 이벤트 기간이 맞지만 아니라는 모달이 뜨는 현상을 해결합니다.

strawberry/src/router/ProtectedRoute.tsx
- fix-#246-protected-route
- 게임 진행 중 로그아웃 => 로그인 시 게임 화면으로 돌아오는 것을 방지
- protected route 안의 navigate 변경
- closed: #246
=> 로그인 시 게임 화면에 돌아가야 한다면 대신 랜딩으로 돌아가게 합니다.

strawberry/src/pages/drawingLanding/hooks/useDrawingBanner.tsx, strawberry/src/pages/drawingLanding/hooks/useDrawingChance.tsx
- fix-#257-drawing-landing-only-bonus
- 보너스 기회만 있는 상태에서 기회가 제대로 조회되지 않아 이를 해결합니다.
- Banner 로직 수정
- Chance 로직 수정
- closed: #257
=> 드로잉 랜딩 페이지에서 보너스 게임만 있을 때 기회가 제대로 조회되지 않는 현상을 해결합니다.

strawberry/src/core/utils/checkOnlyBlank.ts, strawberry/src/core/utils/index.tsx, strawberry/src/pages/expectation/components/ExpectationInput.tsx, strawberry/src/pages/expectation/hooks/logics/useExpectationInput.tsx, strawberry/src/pages/expectation/hooks/useLengthValidation.tsx, strawberry/src/pages/quizPlay/QuizPlayPage.tsx, strawberry/src/pages/quizPlay/components/quizInput/CardInput.tsx, strawberry/src/pages/quizPlay/hooks/logics/useQuizPlayPage.tsx
- fix-#259-input-only-blank
- 문자열을 제출하는 post 요청에서 blank error를 방지하기 위해 코드 추가
- QuizPlay에서 blank만 제출 불가
- Expectation에서 blank만 제출 불가
- QuizPlay에서 blank만 제출 시 모달
- closed: #259
=> 문자열 submit 시에 blank로만 이루어진 경우를 해결합니다.

strawberry/src/core/utils/convertSeconds.tsx, strawberry/src/pages/quizLanding/components/quizBanner/QuizBanner.tsx, strawberry/src/pages/quizLanding/components/quizBanner/QuizBannerTimer.tsx, strawberry/src/pages/quizLanding/hooks/useQuizBanner.tsx, strawberry/src/pages/quizLanding/models/Timer.tsx
- feat-#265-quiz-timer-button
- 선착순 퀴즈 이벤트의 버튼 로직을 추가합니다.
- Timer에 totalSeconds 추가
- isOpened를 사용하여 버튼 활성화 로직 추가
- close: #265
=> 퀴즈 랜딩 페이지에서 타이머에 따른 버튼 활성화 로직을 추가합니다.

strawberry/src/layout/components/header/HeaderMenuButtons.tsx
- fix-#278-header-quiz
- 퀴즈 플레이 화면에서 헤더 퀴즈 탭으로 이동 시의 문제를 해결 
- Link 태그 href로 변경
- closed: #278
=> 퀴즈 플레이 화면에서 헤더 퀴즈 탭으로 이동 시의 문제를 해결합니다. 

strawberry/src/pages/expectation/ExpectationPage.tsx, strawberry/src/pages/expectation/hooks/logics/useExpectationPage.tsx, strawberry/src/pages/expectation/hooks/useExpectationData.tsx
- feat-#84-no-expectations
- 기대평이 없을 경우 404 에러를 처리하고 이에 맞는 컴포넌트를 렌더링
- 에러 핸들링 코드 추가
- 작성된 기대평이 없다는 컴포넌트 렌더링 코드 추가
- closed: #84
=> 기대평 페이지에 작성된 글이 없을 시에 보여줄 컴포넌트를 추가합니다.

strawberry/src/pages/drawingPlay/components/drawingFinish/DrawingInput.tsx
- feat-#291-drawing-input-enter
- 기대평 작성 시 enter를 통해 제출할 수 있도록 합니다.
- enter 이벤트 감지 후 제출
- closed: #291
=> 드로잉 게임의 기대평 작성 시 enter를 통해 제출할 수 있도록 추가합니다.

strawberry/src/core/design_system/styles/Wrapper.tsx, strawberry/src/pages/newCar/NewCarPage.tsx, strawberry/src/pages/newCar/RenderOnViewportEntry.tsx, strawberry/src/pages/newCar/useFirstViewportEntry.ts, strawberry/src/router/router.tsx
feat/#293-lazy-loading
- 사용하지 않는 파일들까지 불러오는 현상을 해결하기 위해 Lazy loading을 추가합니다.
- Observer api를 추가하여, viewport에 들어올 때 로드하도록 변경합니다.
- 이미지에 lazy loading을 추가합니다 (다음 PR- 애니메이션에 같이 올리도록 하겠습니다.)
- 다른 탭에 있는 파일까지 불러오던 네트워크 파일 목록이 확연하게 줄었음을 확인할 수 있다.
- content Load 시간이 줄었음을 확인할 수 있다.
- 뿐만 아니라 스크롤 시에 파일들을 불러오는걸 확인할 수 있다.
[ Lazy Loading 적용 이후]
https://github.com/user-attachments/assets/4cd5781b-6d3b-4c49-8ca9-777b73c161cf
[ Lazy Loading 적용 이전 ]
https://github.com/user-attachments/assets/3e62d669-c360-4549-90b3-3779320b4715
closed: #293
=> feat: Lazy Loading, IntersectionObserver를 추가합니다.
